apiVersion: v2
name: es-sampler
description: Sample documents from a source Elasticsearch cluster into a destination cluster.
type: application
version: 0.1.0
appVersion: "0.1.0"
sources:
  - https://github.com/ruflin/es-sampler
